[package]
name = "ctxruntime"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib", "lib"]
name = "ctxruntime"

[dependencies]
log = "0.4.27"
nom = { version = "8.0.0", features = ["alloc"] }
nom_locate = "5.0.0"
pretty_assertions = "1.4.1"
serde = "1.0.219"
serde_json = "1.0.140"
smol_str = "0.3.2"
thiserror = "2.0.12"
tokio = "1.45.1"
uniffi = { version = "0.29" }

[build-dependencies]
uniffi = { version = "0.29", features = ["build"] }

