[package]
name = "context-runtime"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib", "lib"]
name = "contextFFI"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[[bin]]
name = "uniffi-bindgen-swift"
path = "uniffi-bindgen-swift.rs"


[dependencies]
log = "0.4.27"
nom = { version = "8.0.0", features = ["alloc"] }
nom_locate = "5.0.0"
pretty_assertions = "1.4.1"
serde = "1.0.219"
serde_json = "1.0.140"
smol_str = "0.3.2"
thiserror = "2.0.12"
tokio = "1.45.1"
uniffi = { version = "0.29.3", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.29.3", features = ["build"] }

[package.metadata.uniffi]
cdylib_name = "context_runtime"

[features]
ffi-trace = ["uniffi/ffi-trace"]

[[example]]
name = "debug"
